---
x-lode-config: &lode-config
  DEFAULT_LANG: "${DEFAULT_LANG:-en}"
  LODE_EXTERNAL_URL: "${LODE_EXTERNAL_URL:-}"
  MAX_TENTATIVE: "${MAX_TENTATIVE:-3}"
  VENDOR_CSS: "${VENDOR_CSS:-}"
  VENDOR_NAME: "${VENDOR_NAME:-}"
  VENDOR_URL: "${VENDOR_URL:-}"
  WEBVOWL_EXTERNAL_URL: "${WEBVOWL_EXTERNAL_URL:-}"

services:
  jetty:
    build:
      args:
        <<: [ *lode-config ]
      context: .
      target: jetty
    ports:
      - 8080:8080
    volumes:
      - ./.m2/:/root/.m2/
      - ./src/:/opt/src/

  tomcat:
    build:
      context: .
      target: tomcat
    environment:
      <<: [ *lode-config ]
    ports:
      - 8080:8080
