---
x-lode-config: &lode-config
  LODE_EXTERNAL_URL: http://localhost:8080/lode
  WEBVOWL_EXTERNAL_URL: http://visualdataweb.de/webvowl/#iri=
  USE_HTTPS: "false"

services:
  jetty:
    build:
      args:
        <<: [ *lode-config ]
      context: .
      target: jetty
    ports:
      - 8080:8080
    volumes:
      - ./.m2/:/root/.m2/
      - ./src/:/opt/src/

  tomcat:
    build:
      context: .
      target: tomcat
    environment:
      <<: [ *lode-config ]
    ports:
      - 8080:8080
